Add missing exports of classes & interfaces for production build
Fixes the following error (and presumably the same error for the
translation interfaces):

Error: Error encountered resolving symbol values statically. Reference to a non-exported class
TranslateMessageFormatCompiler. Consider exporting the class (position 11:1 in the original .ts file),
resolving symbol translateModuleForRoot in /Users/unknow/Projects/bio/biopocket-mobile/src/utils/i18n.ts